import "oaidl.idl";
import "ocidl.idl";

/*typedef enum
{
    Opened=0,
    AlreadyOpened,
}DigOpenStatus;
typedef enum
{
    Changed=0,
    NoChanged,
}DigChangeStatus;
*/
[
    object,
    oleautomation, 
    uuid(318C52CD-4A12-4C98-892B-1830B026768D)
]
interface ILspClientLogger :IDispatch {
    [propget] HRESULT IsFatalEnabled([out,retval]boolean*ret);
    [propget] HRESULT IsErrorEnabled([out, retval]boolean* ret);
    [propget] HRESULT IsWarnEnabled([out, retval]boolean* ret);
    [propget] HRESULT IsInfoEnabled([out, retval]boolean* ret);
    [propget] HRESULT IsDebugEnabled([out, retval]boolean* ret);
    [propget] HRESULT IsTraceEnabled([out, retval]boolean* ret);
    HRESULT Trace([in]BSTR message);
    HRESULT Debug([in]BSTR message);
    HRESULT Info([in]BSTR message);
    HRESULT Warn([in]BSTR message);
    HRESULT Error([in]BSTR message);
    HRESULT Fatal([in]BSTR message);
};

[
    object,
    oleautomation,
    uuid(47137F87-E07A-422E-9FB8-F0B13C615D2F)
]
interface ITargetServer :IDispatch
{
    [propget] HRESULT ServerName([out,retval]BSTR*ret);
    [propput] HRESULT ServerName([in]BSTR ServerName);
    [propget] HRESULT RootUri([out, retval]BSTR* ret);
    [propput] HRESULT RootUri([in]BSTR rootUri);
    HRESULT Initialize();
}


[
    object,
    oleautomation,
    uuid(9159F305-06A3-4231-B023-BFF30CE0D9E8)
]
interface IHidemaruLspBackEndServer : IDispatch
{    
    HRESULT CreateTargetServer([out]ITargetServer**targetServer);
    HRESULT Initialize([in]BSTR logFileName, [out, retval] boolean* ret);
    HRESULT GetLogger([out]ILspClientLogger** logger);
    HRESULT Add([in]int x, [in] int y, [out, retval] int* ret);
    HRESULT Finalizer([in]ITargetServer* TargetServer, [in]int reason);
    HRESULT Start([in]ITargetServer* TargetServer,
                  [in]BSTR ExcutablePath,
                  [in]BSTR Arguments,
                  [in]BSTR WorkspaceConfig,
                  [in]BSTR currentSourceCodeDirectory,
                  [out, retval]boolean *ret);
    HRESULT DigOpen([in]ITargetServer* TargetServer,[in]BSTR filename, [in]BSTR text, int contentsVersion);
    HRESULT DigChange([in]ITargetServer* TargetServer, [in]BSTR filename, [in]BSTR text, int contentsVersion);
    HRESULT Completion([in]ITargetServer* TargetServer, [in]BSTR absFilename, [in]hyper line, [in]hyper column, [out, retval]BSTR*ret);
};

[
    uuid(27E4EB65-F8C3-4191-BF62-E46D85964111)
]
library HidemaruLspClient_BackEnd_Lib
{
    importlib("stdole2.tlb");

    [
        uuid(EF516543-D040-46CC-88B3-FD64C09DB652)
    ]
    coclass Server
    {
        [default] interface IHidemaruLspBackEndServer;
    }
}
