import "oaidl.idl";
import "ocidl.idl";

/*typedef enum
{
    Opened=0,
    AlreadyOpened,
}DigOpenStatus;
typedef enum
{
    Changed=0,
    NoChanged,
}DigChangeStatus;
*/
[
    object,
    oleautomation, 
    uuid(318C52CD-4A12-4C98-892B-1830B026768D)
]
interface ILspClientLogger :IDispatch {
    [propget] HRESULT IsFatalEnabled([out,retval]boolean*ret);
    [propget] HRESULT IsErrorEnabled([out, retval]boolean* ret);
    [propget] HRESULT IsWarnEnabled([out, retval]boolean* ret);
    [propget] HRESULT IsInfoEnabled([out, retval]boolean* ret);
    [propget] HRESULT IsDebugEnabled([out, retval]boolean* ret);
    [propget] HRESULT IsTraceEnabled([out, retval]boolean* ret);
    HRESULT Trace([in]BSTR message);
    HRESULT Debug([in]BSTR message);
    HRESULT Info([in]BSTR message);
    HRESULT Warn([in]BSTR message);
    HRESULT Error([in]BSTR message);
    HRESULT Fatal([in]BSTR message);
};

[
    object,
    oleautomation,
    uuid(E8153825-63C2-4C50-9889-0DEB4CFB4033)
]
interface IWorker :IDispatch
{
    HRESULT DigOpen([in]BSTR filename, [in]BSTR text, [in]int contentsVersion);
    HRESULT DigChange([in]BSTR filename, [in]BSTR text, [in]int contentsVersion);
    HRESULT Completion([in]BSTR absFilename, [in]hyper line, [in]hyper column, [out,retval]BSTR*retval);
}


[
    object,
    oleautomation,
    uuid(9159F305-06A3-4231-B023-BFF30CE0D9E8)
]
interface IHidemaruLspBackEndServer : IDispatch
{    
    HRESULT Initialize([in]BSTR logFileName, [out, retval] boolean* ret);
    HRESULT GetLogger([out]ILspClientLogger** logger);
    HRESULT Add([in]int x, [in] int y, [out, retval] int* ret);
    HRESULT CreateWorker([in]BSTR ServerName,
                  [in]BSTR ExcutablePath,
                  [in]BSTR Arguments,
                  [in]BSTR RootUri,
                  [in]BSTR WorkspaceConfig,
                  [out] IWorker** worker);
    HRESULT DestroyWorker([in]IWorker *worker);
};

[
    uuid(27E4EB65-F8C3-4191-BF62-E46D85964111)
]
library HidemaruLspClient_BackEnd_Lib
{
    importlib("stdole2.tlb");

    [
        uuid(EF516543-D040-46CC-88B3-FD64C09DB652)
    ]
    coclass Server
    {
        [default] interface IHidemaruLspBackEndServer;
    }
}
