import "oaidl.idl";
import "ocidl.idl";

/*typedef enum
{
    Opened=0,
    AlreadyOpened,
}DigOpenStatus;
typedef enum
{
    Changed=0,
    NoChanged,
}DigChangeStatus;
*/
[
    object,
    oleautomation, 
    uuid(318C52CD-4A12-4C98-892B-1830B026768D)
]
interface ILspClientLogger :IDispatch {
    [propget] HRESULT IsFatalEnabled([out,retval]boolean*ret);
    [propget] HRESULT IsErrorEnabled([out, retval]boolean* ret);
    [propget] HRESULT IsWarnEnabled([out, retval]boolean* ret);
    [propget] HRESULT IsInfoEnabled([out, retval]boolean* ret);
    [propget] HRESULT IsDebugEnabled([out, retval]boolean* ret);
    [propget] HRESULT IsTraceEnabled([out, retval]boolean* ret);
    HRESULT Trace([in]BSTR message);
    HRESULT Debug([in]BSTR message);
    HRESULT Info([in]BSTR message);
    HRESULT Warn([in]BSTR message);
    HRESULT Error([in]BSTR message);
    HRESULT Fatal([in]BSTR message);
};

///////////////////////////////////////////////////////////////////////////
/// IPublishDiagnosticsParams
///////////////////////////////////////////////////////////////////////////
 enum DiagnosticSeverity
{
    Error = 1,
    Warning = 2,
    Information = 3,
    Hint = 4
};

[
    object,
    oleautomation,
    uuid(53A84500-EAF3-4248-B167-D9921EE8AB51)
]
interface IPosition:IDispatch
{
    [propget] HRESULT character([out,retval]hyper*ret);
    [propget] HRESULT line([out, retval]hyper* ret);
};

[
    object,
    oleautomation,
    uuid(D3E64D92-3ABB-494B-A26F-A856DFE54D54)
]
interface IRange :IDispatch
{
    [propget] HRESULT start([out, retval]IPosition** ret);
    [propget] HRESULT end([out, retval]IPosition** ret);
};

[
    object,
    oleautomation,
    uuid(5DC500BE-636F-4886-8FF5-6359D46B3342)
]
interface IDiagnostic :IDispatch
{
    [propget] HRESULT range([out, retval]IRange** ret);
    [propget] HRESULT severity([out,retval]enum DiagnosticSeverity*ret);
    [propget] HRESULT code([out, retval]BSTR* ret);
    [propget] HRESULT source([out, retval]BSTR* ret);
    [propget] HRESULT message([out, retval]BSTR* ret);
};

[
    object,
    oleautomation,
    uuid(C5E68A27-29AD-4D35-8E12-7C5712D781D3)
]
interface IPublishDiagnosticsParams :IDispatch
{
    [propget] HRESULT uri([out, retval]BSTR* ret);
    [propget] HRESULT version([out, retval]hyper* ret);    
    [propget] HRESULT Length([out,retval]hyper*length);
    HRESULT Item([in]hyper index, [out,retval]IDiagnostic**ret);    
};

[
    object,
    oleautomation,
    uuid(80056854-4f16-4109-85b5-79feb5e06e27)
]
interface IPublishDiagnosticsParamsContainer :IDispatch {
    [propget] HRESULT Length([out,retval]hyper*length);
    HRESULT Item([in]hyper index, [out, retval]IPublishDiagnosticsParams** ret);
};



///////////////////////////////////////////////////////////////////////////
/// IWorker
///////////////////////////////////////////////////////////////////////////
[
    object,
    oleautomation,
    uuid(E8153825-63C2-4C50-9889-0DEB4CFB4033)
]
interface IWorker :IDispatch 
{
    HRESULT DidOpen([in]BSTR absFilename, [in]BSTR text, [in]int contentsVersion);
    HRESULT DidChange([in]BSTR absFilename, [in]BSTR text, [in]int contentsVersion);
    HRESULT DidClose([in]BSTR absFilename);
    HRESULT Completion([in]BSTR absFilename, [in]hyper line, [in]hyper column, [out,retval]BSTR*retval);
    HRESULT PullDiagnosticsParams([out, retval] IPublishDiagnosticsParamsContainer** ret);
}

[
    object,
    oleautomation,
    uuid(9159F305-06A3-4231-B023-BFF30CE0D9E8)
]
interface IHidemaruLspBackEndServer : IDispatch
{    
    HRESULT Initialize([in]BSTR logFileName, [out, retval] boolean* ret);
    HRESULT GetLogger([out,retval]ILspClientLogger** logger);
    HRESULT Add([in]int x, [in] int y, [out, retval] int* ret);
    HRESULT CreateWorker([in]BSTR ServerName,
                  [in]BSTR ExcutablePath,
                  [in]BSTR Arguments,
                  [in]BSTR RootUri,
                  [in]BSTR WorkspaceConfig,
                  [in]hyper HidemaruProcessId,
                  [out,retval] IWorker** worker);
    HRESULT DestroyWorker([in]IWorker *worker);
};

[
    uuid(27E4EB65-F8C3-4191-BF62-E46D85964111)
]
library HidemaruLspClient_BackEndContract
{
    importlib("stdole2.tlb");

    [
        //version(1.0),
        //progid("HidemaruLSPClient_BackEnd.HidemaruLspBackEndServer"),
        uuid(EF516543-D040-46CC-88B3-FD64C09DB652)
    ]
    coclass Server
    {
        [default] interface IHidemaruLspBackEndServer;
    }
}
