import "oaidl.idl";
import "ocidl.idl";
import "basetsd.h";

/*typedef enum
{
    Opened=0,
    AlreadyOpened,
}DigOpenStatus;
typedef enum
{
    Changed=0,
    NoChanged,
}DigChangeStatus;
*/
[
    object,
    oleautomation,
    uuid(318C52CD-4A12-4C98-892B-1830B026768D)
]
interface ILspClientLogger :IDispatch {
    [propget] HRESULT IsFatalEnabled([out,retval]boolean*ret);
    [propget] HRESULT IsErrorEnabled([out, retval]boolean* ret);
    [propget] HRESULT IsWarnEnabled([out, retval]boolean* ret);
    [propget] HRESULT IsInfoEnabled([out, retval]boolean* ret);
    [propget] HRESULT IsDebugEnabled([out, retval]boolean* ret);
    [propget] HRESULT IsTraceEnabled([out, retval]boolean* ret);
    HRESULT Trace([in]BSTR message);
    HRESULT Debug([in]BSTR message);
    HRESULT Info([in]BSTR message);
    HRESULT Warn([in]BSTR message);
    HRESULT Error([in]BSTR message);
    HRESULT Fatal([in]BSTR message);
};

[
    object,
    oleautomation,
    uuid(53A84500-EAF3-4248-B167-D9921EE8AB51)
]
interface IPosition :IDispatch
{
    [propget] HRESULT character([out, retval]hyper* ret);
    [propget] HRESULT line([out, retval]hyper* ret);
};

[
    object,
    oleautomation,
    uuid(D3E64D92-3ABB-494B-A26F-A856DFE54D54)
]
interface IRange :IDispatch
{
    [propget] HRESULT start([out, retval]IPosition** ret);
    [propget] HRESULT end([out, retval]IPosition** ret);
};

///////////////////////////////////////////////////////////////////////////
/// IPublishDiagnosticsParams
///////////////////////////////////////////////////////////////////////////
 enum DiagnosticSeverity
{
    Error = 1,
    Warning = 2,
    Information = 3,
    Hint = 4
};

[
    object,
    oleautomation,
    uuid(5DC500BE-636F-4886-8FF5-6359D46B3342)
]
interface IDiagnostic :IDispatch
{
    [propget] HRESULT range([out, retval]IRange** ret);
    [propget] HRESULT severity([out,retval]enum DiagnosticSeverity*ret);
    [propget] HRESULT code([out, retval]BSTR* ret);
    [propget] HRESULT source([out, retval]BSTR* ret);
    [propget] HRESULT message([out, retval]BSTR* ret);
};

[
    object,
    oleautomation,
    uuid(C5E68A27-29AD-4D35-8E12-7C5712D781D3)
]
interface IPublishDiagnosticsParams :IDispatch
{
    [propget] HRESULT uri([out, retval]BSTR* ret);
    [propget] HRESULT version([out, retval]hyper* ret);
    [propget] HRESULT Length([out,retval]hyper*length);
    HRESULT Item([in]hyper index, [out,retval]IDiagnostic**ret);
};

[
    object,
    oleautomation,
    uuid(80056854-4f16-4109-85b5-79feb5e06e27)
]
interface IPublishDiagnosticsParamsContainer :IDispatch {
    [propget] HRESULT Length([out,retval]hyper*length);
    HRESULT Item([in]hyper index, [out, retval]IPublishDiagnosticsParams** ret);
};


///////////////////////////////////////////////////////////////////////////
/// Definition
///////////////////////////////////////////////////////////////////////////
[
    object,
    oleautomation,
    uuid(53607e16-3217-42ac-85e1-15fa73ea4443)
]
interface ILocation : IDispatch {
    [propget] HRESULT uri([out, retval]BSTR* ret);
    [propget] HRESULT range([out,retval]IRange**ret);
};

[
    object,
    oleautomation,
    uuid(9eb0d011-b352-4972-830b-b48ac560471e)
]
interface ILocationContainer : IDispatch{
    [propget] HRESULT Length([out, retval]hyper* length);
    HRESULT Item([in]hyper index, [out, retval]ILocation** ret);
};

///////////////////////////////////////////////////////////////////////////
/// Provider
///////////////////////////////////////////////////////////////////////////
[
    object,
    oleautomation,
    uuid(0ad45c64-1c79-445a-b089-975a2240afe8)
]
interface IServerCapabilities : IDispatch {
    [propget] HRESULT CompletionProvider([out, retval]boolean* ret);
    [propget] HRESULT HoverProvider([out, retval]boolean* ret);
    [propget] HRESULT SignatureHelpProvider([out, retval]boolean* ret);
    [propget] HRESULT DeclarationProvider([out, retval]boolean* ret);
    [propget] HRESULT DefinitionProvider([out, retval]boolean* ret);
    [propget] HRESULT TypeDefinitionProvider([out, retval]boolean* ret);
    [propget] HRESULT ImplementationProvider([out, retval]boolean* ret);
    [propget] HRESULT ReferencesProvider([out, retval]boolean* ret);
    [propget] HRESULT DocumentHighlightProvider([out, retval]boolean* ret);
    [propget] HRESULT DocumentSymbolProvider([out, retval]boolean* ret);
    [propget] HRESULT CodeActionProvider([out, retval]boolean* ret);
    [propget] HRESULT CodeLensProvider([out, retval]boolean* ret);
    [propget] HRESULT DocumentLinkProvider([out, retval]boolean* ret);
    [propget] HRESULT ColorProvider([out, retval]boolean* ret);
    [propget] HRESULT DocumentFormattingProvider([out, retval]boolean* ret);
    [propget] HRESULT DocumentRangeFormattingProvider([out, retval]boolean* ret);
    [propget] HRESULT DocumentOnTypeFormattingProvider([out, retval]boolean* ret);
    [propget] HRESULT RenameProvider([out, retval]boolean* ret);
    [propget] HRESULT FoldingRangeProvider([out, retval]boolean* ret);
    [propget] HRESULT ExecuteCommandProvider([out, retval]boolean* ret);
    [propget] HRESULT SelectionRangeProvider([out, retval]boolean* ret);
    [propget] HRESULT LinkedEditingRangeProvider([out, retval]boolean* ret);
    [propget] HRESULT CallHierarchyProvider([out, retval]boolean* ret);
    [propget] HRESULT SemanticTokensProvider([out, retval]boolean* ret);
    [propget] HRESULT MonikerProvider([out, retval]boolean* ret);
    [propget] HRESULT WorkspaceSymbolProvider([out, retval]boolean* ret);
}

///////////////////////////////////////////////////////////////////////////
/// Hover
///////////////////////////////////////////////////////////////////////////
enum MarkupKind{
    PlainText=0,
    Markdown=1,
};

[
    object,
    oleautomation,
    uuid(d9878138-3fb0-4afc-8955-cff67f86cfec)
]
interface IMarkupContent:IDispatch
{
    [propget] HRESULT kind([out,retval]enum MarkupKind *ret);
    [propget] HRESULT value([out, retval]BSTR* ret);
};

[
    object,
    oleautomation,
    uuid(6d7d5a32-8bdf-4124-be0f-71094a5f6bdb)
]
interface IHover : IDispatch {
    [propget] HRESULT contents([out,retval]IMarkupContent**ret);
    [propget] HRESULT range([out, retval]IRange** ret);
};


///////////////////////////////////////////////////////////////////////////
/// IWorker
///////////////////////////////////////////////////////////////////////////
[
    object,
    oleautomation,
    uuid(E8153825-63C2-4C50-9889-0DEB4CFB4033)
]
interface IWorker :IDispatch
{
    [propget] HRESULT ServerCapabilities([out, retval]IServerCapabilities** ret);

    HRESULT DidOpen([in]BSTR absFilename, [in]BSTR text, [in]int contentsVersion);
    HRESULT DidChange([in]BSTR absFilename, [in]BSTR text, [in]int contentsVersion);
    HRESULT DidClose([in]BSTR absFilename);
    HRESULT Completion([in]BSTR absFilename, [in]hyper line, [in]hyper column, [out,retval]BSTR*retval);
    HRESULT PullDiagnosticsParams([out, retval] IPublishDiagnosticsParamsContainer** ret);
    HRESULT Declaration([in]BSTR absFilename, [in]hyper line, [in]hyper column, [out, retval]ILocationContainer** ret);
    HRESULT Definition([in]BSTR absFilename, [in]hyper line, [in]hyper column, [out,retval]ILocationContainer**ret);
    HRESULT TypeDefinition([in]BSTR absFilename, [in]hyper line, [in]hyper column, [out, retval]ILocationContainer** ret);
    HRESULT Implementation([in]BSTR absFilename, [in]hyper line, [in]hyper column, [out, retval]ILocationContainer** ret);
    HRESULT References([in]BSTR absFilename, [in]hyper line, [in]hyper column, [out, retval]ILocationContainer** ret);
    HRESULT Hover([in]BSTR absFilename, [in]hyper line, [in]hyper column, [out,retval]IHover**ret);
}

[
    object,
    oleautomation,
    uuid(9159F305-06A3-4231-B023-BFF30CE0D9E8)
]
interface IHidemaruLspBackEndServer : IDispatch
{
    HRESULT Initialize(/*[in]BSTR logFileName,*/ [out, retval] boolean* ret);
    HRESULT GetLogger([out,retval]ILspClientLogger** logger);
    HRESULT EnableSendCrashReport([in] boolean value);
    //Debug Methid.
    HRESULT Add([in]int x, [in] int y, [out, retval] int* ret);
    HRESULT CreateWorker([in]BSTR ServerName,
                  [in]BSTR ExcutablePath,
                  [in]BSTR Arguments,
                  [in]BSTR RootUri,
                  [in]BSTR WorkspaceConfig,
                  [in]hyper HidemaruProcessId,
                  [out,retval] IWorker** worker);
    HRESULT DestroyWorker([in]IWorker *worker);
};

[
    uuid(27E4EB65-F8C3-4191-BF62-E46D85964111)
]
library HidemaruLspClient_BackEndContract
{
    importlib("stdole2.tlb");

    [
        //version(1.0),
        //progid("HidemaruLSPClient_BackEnd.HidemaruLspBackEndServer"),
        uuid(EF516543-D040-46CC-88B3-FD64C09DB652)
    ]
    coclass Server
    {
        [default] interface IHidemaruLspBackEndServer;
    }
}
